### ISSUE TITLE
Presented view controller is dismissed if tapped 

### ISSUE THREAD

**Issue by Sumolari** [kylebshr/ElegantPresentations#2]
If option `DismissOnDimmingViewTap` is set and you tap on the presented view controller (specifically, on a region which has no any other gesture recognizer) it is dismissed.

I cannot upload a demo project highlighting this right now but it's as easy as creating a UITableViewController with some rows (not enough to cover the entire view displayed), presenting it with ElegrantPresentations (with `DismissOnDimmingViewTap` enabled)  and then tapping of the background of the table view: table view controller will be dismissed.

I've fixed it by setting a delegate for the dismiss gesture recognizer and only handling touches that are not in presented view controller's frame: [pull request](https://github.com/kylebshr/ElegantPresentations/pull/1), sumolari@bc6ba9dc86b2d222bdec2f51a1f0dd9d9ac95f88.

**Comment by kylebshr** [comment]
Nice catch! Looks like a reasonable solution. Thanks for the first PR on any of my open source projects 🎉
