### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by bb-git** [kylebshr/ElegantPresentations#6]
Does this library compile with XCode 8 and Swift 3?

**Comment by ex3ndr** [comment]
In my case not, it is crushing because `presenting: UIViewController` is nil

**Comment by kylebshr** [comment]
Sorry, currently finishing up my last semester of school and in the midst or organizing a hackathon 😅 But I'll take some time very soon to pay attention to this.

**Comment by kylebshr** [comment]
Version 2.0 should work with Swift 3 and iOS 10, please let me know if you're still running into issues!
